# .zipline/pipeline.yml

name: "Secret Value Check"
description: "A pipeline that checks the value of a specific secret."

steps:
  - name: "A - Prepare Environment"
    image: "alpine:latest"
    run: |
      echo "Preparing environment..."
      # This step just verifies the file exists
      ls index.js
      echo "Preparation complete."

  - name: "B - Check Secret Value"
    needs:
      - "A - Prepare Environment"
    image: "alpine:latest"
    # This 'secrets' key tells the runner to inject the GOKU secret
    secrets:
      - "GOKU"
    run: |
      echo "Checking secret value..."
      # The secret is now available as an environment variable
      if [ -z "$GOKU" ]; then
        echo "Error: GOKU secret is not set."
        exit 1
      elif [ "$GOKU" = "goku" ]; then
        echo "OK"
        echo "Secret value is correct."
      else
        echo "Secret GOKU does not have the expected value."
        exit 1
      fi
