# .zipline/pipeline.yml

name: "Pipeline Failure Test"
description: "A pipeline designed to test the system's ability to handle step failures gracefully."

steps:
  - name: "1. Setup Environment"
    image: "alpine:latest"
    run: |
      echo "Setup step starting..."
      echo "This step will succeed."
      sleep 2
      echo "Setup complete."

  - name: "2. Intentionally Failing Step"
    image: "alpine:latest"
    run: |
      echo "This step will now fail by trying to run a command that doesn't exist."
      this-command-does-not-exist
      echo "This line should never be printed."

  - name: "3. Cleanup (Should Not Run)"
    image: "alpine:latest"
    run: |
      echo "!!! This step should never execute because the previous step failed."
      echo "If you see this message, the failure handling is not working correctly."

