name: "Parallel DAG Test"
description: "Test true parallel execution of independent steps"
steps:
  # Three independent steps that should run in parallel
  - name: "step-a"
    image: "alpine:latest"
    run: |
      echo "Step A starting at $(date)"
      sleep 5
      echo "Step A completed at $(date)"

  - name: "step-b"
    image: "alpine:latest"
    run: |
      echo "Step B starting at $(date)"
      sleep 5
      echo "Step B completed at $(date)"

  - name: "step-c"
    image: "alpine:latest"
    run: |
      echo "Step C starting at $(date)"
      sleep 5
      echo "Step C completed at $(date)"

  # Step that depends on all three above (should start only after A, B, C complete)
  - name: "step-d"
    image: "alpine:latest"
    needs: ["step-a", "step-b", "step-c"]
    run: |
      echo "Step D starting at $(date) - depends on A, B, C"
      sleep 3
      echo "Step D completed at $(date)"

  # Two steps that depend only on D (should run in parallel)
  - name: "step-e"
    image: "alpine:latest"
    needs: ["step-d"]
    run: |
      echo "Step E starting at $(date) - depends on D"
      sleep 4
      echo "Step E completed at $(date)"

  - name: "step-f"
    image: "alpine:latest"
    needs: ["step-d"]
    run: |
      echo "Step F starting at $(date) - depends on D"
      sleep 4
      echo "Step F completed at $(date)"
