name: "Comprehensive Live Log Test"
description: "A long-running pipeline with multiple stages to test the stability and real-time capabilities of the log streaming system."

steps:
  - name: "1. Initializing Build Environment"
    image: "alpine:latest"
    run: |
      echo "Build started at: $(date)"
      echo "----------------------------------------"
      echo "Fetching system information..."
      uname -a
      echo "Checking disk space..."
      df -h
      echo "Environment setup complete."
      echo "----------------------------------------"

  - name: "2. Simulating Long Code Compilation (120 seconds)"
    image: "alpine:latest"
    run: |
      echo "Starting simulated compilation process (extended)..."
      for i in $(seq 1 12); do
        echo "Compiling module $i of 12..."
        sleep 10
        echo "Module $i compiled successfully."
      done
      echo "âœ… All modules compiled. Total duration: 120 seconds."

  - name: "3. Running Unit & Integration Tests"
    image: "alpine:latest"
    run: |
      echo "--- Running Test Suite ---"
      sleep 2
      echo "[PASS] âœ… User authentication test"
      sleep 2
      echo "[PASS] âœ… Database connection test"
      sleep 2
      echo "[WARN] âš ï¸ Email service test skipped (API key not found)"
      sleep 2
      echo "[PASS] âœ… API endpoint validation test"
      echo "--- Test Suite Complete ---"

  - name: "4. Generating an Error Message"
    image: "alpine:latest"
    run: |
      echo "This step will now generate a non-fatal error message to stderr."
      echo "This is a test error message" >&2
      echo "The step will still succeed, but the error should be visible in the logs."

  - name: "5. Packaging Application for Deployment (60 seconds)"
    image: "alpine:latest"
    run: |
      echo "Starting final packaging process (extended)..."
      echo "Compressing assets..."
      sleep 20
      echo "Creating Docker image layer..."
      sleep 20
      echo "Pushing to artifact registry..."
      sleep 20
      echo "ðŸš€ Application packaged and ready for deployment."

  - name: "6. Finalizing and Cleanup"
    image: "alpine:latest"
    run: |
      echo "----------------------------------------"
      echo "Pipeline finished at: $(date)"
      echo "Build successful. All stages completed."
      echo "----------------------------------------"
