name: "Simple Artifact Test"
steps:
  - name: "Create Build Artifact"
    image: "alpine:latest"
    run: |
      echo "Creating a build directory and a sample file..."
      mkdir ./build
      echo "This is a test artifact." > ./build/hello.txt
      echo "Artifact created."
    artifacts:
      - name: "output-files"
        path: "./build"
