name: "Multi-Stage Pipeline"
steps:
  - name: "Run Unit Tests"
    image: "node:18"
    run: "npm test"

  - name: "Lint Code"
    image: "node:18"
    run: "npm run lint"

  - name: "Build Application"
    image: "node:18"
    # This step will only run after both tests and linting succeed
    needs:
      - "Run Unit Tests"
      - "Lint Code"
    run: "npm run build"

  - name: "Deploy to Staging"
    image: "aws-cli"
    # This step depends on the build finishing
    needs:
      - "Build Application"
    run: "aws s3 sync ./dist s3://staging-bucket"
