# .zipline/pipeline.yml

name: "DAG Error Handling Test"
description: "A pipeline to test if the orchestrator correctly handles a failed step and its dependents."

steps:
  - name: "A - Run Backend Unit Tests"
    image: "alpine:latest"
    run: |
      echo "Starting backend unit tests..."
      sleep 10
      echo "Backend unit tests passed. This step should succeed."

  - name: "B - Run Frontend Unit Tests (Will Fail)"
    image: "alpine:latest"
    run: |
      echo "Starting frontend unit tests..."
      sleep 5
      echo "This step will now fail intentionally."
      exit 1

  - name: "C - Lint Code"
    image: "alpine:latest"
    run: |
      echo "Linting code..."
      sleep 8
      echo "Linting complete. This independent step should succeed."

  - name: "D - Build Application (Should Not Run)"
    # This step depends on the failed step "B"
    needs:
      - "A - Run Backend Unit Tests"
      - "B - Run Frontend Unit Tests (Will Fail)"
      - "C - Lint Code"
    image: "alpine:latest"
    run: |
      echo "!!! ERROR: This step should never execute because step B failed."

  - name: "E - Deploy to Staging (Should Not Run)"
    # This step depends on a step that will not run
    needs:
      - "D - Build Application (Should Not Run)"
    image: "alpine:latest"
    run: |
      echo "!!! ERROR: This step should never execute."

