# .zipline/pipeline.yml

name: "Website Build and Deploy Pipeline"
description: "A full CI/CD pipeline that builds, tests, and deploys a web application."

# This pipeline will only run on pushes to the 'main' branch.
on:
  push:
    branches:
      - dev

steps:
  # --- Stage 1: Initial Checks (Run in Parallel) ---
  - name: "A - Lint Code"
    image: "node:18-alpine"
    run: |
      echo "Running linters..."
      # In a real project, this would be: npm install && npm run lint
      sleep 10
      echo "Linting complete."

  - name: "B - Run Unit Tests"
    image: "node:18-alpine"
    run: |
      echo "Running unit tests..."
      # In a real project, this would be: npm install && npm test
      sleep 15
      echo "Unit tests passed."

  # --- Stage 2: Build (Waits for checks, produces artifact) ---
  - name: "C - Build Application"
    needs:
      - "A - Lint Code"
      - "B - Run Unit Tests"
    image: "node:18-alpine"
    run: |
      echo "All checks passed. Building application..."
      # Simulate creating a build output directory
      mkdir -p ./dist
      echo "<html><body><h1>Hello, Zipline!</h1></body></html>" > ./dist/index.html
      echo "Application built successfully."
    artifacts:
      name: "website-build"
      paths:
        - "./dist"

  # --- Stage 3: Deploy (Final step) ---
  - name: "D - Deploy to Production"
    needs:
      - "C - Build Application"
    image: "alpine:latest"
    secrets:
      - "DEPLOYMENT_TOKEN"
    run: |
      echo "Deploying to production server..."
      if [ -z "$DEPLOYMENT_KEY" ]; then
        echo "Error: DEPLOYMENT_TOKEN secret is not set."
        exit 1
      else
        echo "Authentication successful. Deployment starting..."
        sleep 10
        echo "🚀 Successfully deployed to production!"
      fi


