name: "Build and Test Pipeline"
description: "Automated CI/CD pipeline"

steps:
  - name: "Install Dependencies"
    image: "node:18-alpine"
    run: "npm install"

  - name: "Run Tests"
    image: "node:18-alpine"
    run: "npm test"

  - name: "Build Application"
    image: "node:18-alpine"
    run: "npm run build"
