# .zipline/pipeline.yml

name: "Simple Build with Artifacts"
description: "A simple pipeline that creates a build directory and saves it as an artifact."

steps:
  - name: "A - Create Log Artifact"
    image: "alpine:latest"
    run: |
      echo "Creating a log file for this run..."
      echo "Pipeline started at $(date)" > run.log
      echo "Log file created."
    artifacts:
      name: "run-log"
      paths:
        - "./run.log"

  - name: "B - Create Build Directory"
    image: "alpine:latest"
    run: |
      echo "Creating build directory from index.js..."
      mkdir ./dist
      cp index.js ./dist/app.js
      echo "Build directory created."
    artifacts:
      name: "application-build"
      paths:
        - "./dist"

  - name: "C - Package for Deployment"
    needs:
      - "A - Create Log Artifact"
      - "B - Create Build Directory"
    image: "alpine:latest"
    run: |
      echo "Packaging final artifacts for deployment..."
      sleep 5
      echo "Packaging complete."

