# .zipline/pipeline.yml

name: "Production Deployment Pipeline"
description: "A pipeline that builds and deploys the application to production."

# This 'on' key tells the orchestrator to ONLY run this pipeline
# for pushes to the 'main' branch.
on:
  push:
    branches:
      - main
      - dev

steps:
  - name: "Build Application"
    image: "alpine:latest"
    run: |
      echo "Starting production build..."
      # This simulates creating a build artifact
      mkdir ./build
      cp index.js ./build/app.js
      echo "Build complete."
    artifacts:
      name: "production-build"
      paths:
        - "./build"

  - name: "Deploy to Production"
    needs:
      - "Build Application"
    image: "alpine:latest"
    secrets:
      - "DEPLOYMENT_KEY"
    run: |
      echo "Deploying to production server..."
      if [ -z "$DEPLOYMENT_KEY" ]; then
        echo "Error: Production deployment key is not set."
        exit 1
      else
        echo "Authentication successful. Starting deployment..."
        sleep 10
        echo "🚀 Deployment to production complete."
      fi


