# .zipline/pipeline.yml

name: "Simple DAG with Artifact"
description: "A simple pipeline that validates a file, creates a build artifact, and finalizes."

steps:
  - name: "A - Validate File"
    image: "alpine:latest"
    run: |
      echo "Checking for index.js..."
      ls index.js
      echo "File found."

  - name: "B - Create Build Artifact"
    needs:
      - "A - Validate File"
    image: "alpine:latest"
    run: |
      echo "Creating build directory..."
      mkdir ./dist
      cp index.js ./dist/app.js
      echo "Build directory created."
    artifacts:
      name: "application-package"
      paths:
        - "./dist"

  - name: "C - Finalize"
    needs:
      - "B - Create Build Artifact"
    image: "alpine:latest"
    run: |
      echo "Packaging and finalization complete."
      sleep 5
      echo "Pipeline finished."
